import { DbState } from './types';

export const initialDb: DbState = {
  users: [],
  questions: [
    {
      questionId: 'q-001',
      boothId: 'b-01',
      title: '綿菓子の色',
      difficulty: 1,
      point: 1,
      questionText: 'わたあめ工房で人気の綿菓子の色は何色？',
      hint: '看板の色を見てみよう。',
      imageUrl: '',
      correctAnswer: 'pink',
      options: ['pink', 'blue', 'green', 'white'],
      createdAt: new Date('2026-07-01T00:00:00.000Z').toISOString(),
    },
    {
      questionId: 'q-002',
      boothId: 'b-01',
      title: '砂糖の量',
      difficulty: 2,
      point: 2,
      questionText: '綿菓子 1 個に使う砂糖のイメージはどれ？',
      hint: '甘さのインパクトで考えてみよう。',
      imageUrl: '',
      correctAnswer: 'a lot',
      options: ['a little', 'a lot', 'none', 'only salt'],
      createdAt: new Date('2026-07-01T00:00:00.000Z').toISOString(),
    },
    {
      questionId: 'q-003',
      boothId: 'b-02',
      title: '足音の数',
      difficulty: 3,
      point: 3,
      questionText: 'お化け屋敷の入口で鳴る足音は何回？',
      hint: '演出のリズムを数えてみよう。',
      imageUrl: '',
      correctAnswer: '3',
      options: ['2', '3', '4', '5'],
      createdAt: new Date('2026-07-01T00:00:00.000Z').toISOString(),
    },
    {
      questionId: 'q-004',
      boothId: 'b-03',
      title: '液体の変化',
      difficulty: 4,
      point: 4,
      questionText: '科学ラボの実験で色が変わる液体は何系？',
      hint: 'pH の変化を意識しよう。',
      imageUrl: '',
      correctAnswer: 'acid base indicator',
      options: ['acid base indicator', 'oil', 'water', 'alcohol'],
      createdAt: new Date('2026-07-01T00:00:00.000Z').toISOString(),
    },
    {
      questionId: 'q-005',
      boothId: 'b-03',
      title: 'ラボの法則',
      difficulty: 5,
      point: 5,
      questionText: '実験で大切な安全装備は何？',
      hint: '目を守るものを思い出そう。',
      imageUrl: '',
      correctAnswer: 'goggles',
      options: ['goggles', 'sandals', 'cap', 'gloves only'],
      createdAt: new Date('2026-07-01T00:00:00.000Z').toISOString(),
    },
  ],
  booths: [
    {
      boothId: 'b-01',
      boothName: 'わたあめ工房',
      description: '甘い香りの模擬店。QR を読み取って挑戦しよう。',
      location: '体育館前',
    },
    {
      boothId: 'b-02',
      boothName: 'お化け屋敷',
      description: '不気味な演出の中に隠れたクイズを解こう。',
      location: '旧校舎 2F',
    },
    {
      boothId: 'b-03',
      boothName: '科学ラボ',
      description: '理科室を使った体験型アトラクション。',
      location: '理科室',
    },
  ],
  answers: [],
  questionViews: [],
  boothVisits: [],
  exchangeTokens: [],
  exchanges: [],
  adminLogs: [],
  analytics: [],
};